In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('data.csv', ',' ,error_bad_lines=False)

b'Skipping line 2810: expected 2 fields, saw 5\nSkipping line 4641: expected 2 fields, saw 5\nSkipping line 7171: expected 2 fields, saw 5\nSkipping line 11220: expected 2 fields, saw 5\nSkipping line 13809: expected 2 fields, saw 5\nSkipping line 14132: expected 2 fields, saw 5\nSkipping line 14293: expected 2 fields, saw 5\nSkipping line 14865: expected 2 fields, saw 5\nSkipping line 17419: expected 2 fields, saw 5\nSkipping line 22801: expected 2 fields, saw 5\nSkipping line 25001: expected 2 fields, saw 5\nSkipping line 26603: expected 2 fields, saw 5\nSkipping line 26742: expected 2 fields, saw 5\nSkipping line 29702: expected 2 fields, saw 5\nSkipping line 32767: expected 2 fields, saw 5\nSkipping line 32878: expected 2 fields, saw 5\nSkipping line 35643: expected 2 fields, saw 5\nSkipping line 36550: expected 2 fields, saw 5\nSkipping line 38732: expected 2 fields, saw 5\nSkipping line 40567: expected 2 fields, saw 5\nSkipping line 40576: expected 2 fields, saw 5\nSkipping line 

b'Skipping line 525174: expected 2 fields, saw 5\nSkipping line 526251: expected 2 fields, saw 5\nSkipping line 529611: expected 2 fields, saw 5\nSkipping line 531398: expected 2 fields, saw 5\nSkipping line 534146: expected 2 fields, saw 5\nSkipping line 544954: expected 2 fields, saw 5\nSkipping line 553002: expected 2 fields, saw 5\nSkipping line 553883: expected 2 fields, saw 5\nSkipping line 553887: expected 2 fields, saw 5\nSkipping line 553915: expected 2 fields, saw 5\nSkipping line 554172: expected 2 fields, saw 5\nSkipping line 563534: expected 2 fields, saw 5\nSkipping line 565191: expected 2 fields, saw 5\nSkipping line 574108: expected 2 fields, saw 5\nSkipping line 574412: expected 2 fields, saw 5\nSkipping line 575985: expected 2 fields, saw 5\nSkipping line 580091: expected 2 fields, saw 5\nSkipping line 582682: expected 2 fields, saw 5\nSkipping line 585885: expected 2 fields, saw 5\nSkipping line 590171: expected 2 fields, saw 5\nSkipping line 591924: expected 2 field

In [3]:
df.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [4]:
df.isnull().sum()

password    1
strength    0
dtype: int64

In [5]:
df[df['password'].isnull()]

password  strength
367579      NaN         0

In [6]:
df.dropna(inplace=True)

In [7]:
password_tuple=np.array(df)

In [8]:
password_tuple

array([['kzde5577', 1],
       ['kino3434', 1],
       ['visi7k1yr', 1],
       ...,
       ['184520socram', 1],
       ['marken22a', 1],
       ['fxx4pw4g', 1]], dtype=object)

In [9]:
import random

In [10]:
random.shuffle(password_tuple)

In [11]:
y=[i[1] for i in password_tuple]

In [12]:
y

[1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 0,
 1,
 0,
 2,
 2,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 0,
 1,
 1,
 1,
 1,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 0,
 1,
 0,
 0,


In [13]:
X=[i[0] for i in password_tuple]
X

['kzde5577',
 'kino3434',
 'kino3434',
 'megzy123',
 'kino3434',
 'AVYq1lDE4MgAZfNt',
 'u6c8vhow',
 'kzde5577',
 'megzy123',
 'kzde5577',
 'as326159',
 'u6c8vhow',
 'kzde5577',
 'universe2908',
 'AVYq1lDE4MgAZfNt',
 'megzy123',
 'lamborghin1',
 'universe2908',
 '612035180tok',
 '52558000aaa',
 'u6c8vhow',
 'jytifok873',
 '612035180tok',
 '52558000aaa',
 'kzde5577',
 '52558000aaa',
 'asv5o9yu',
 '0169395484a',
 'AVYq1lDE4MgAZfNt',
 '6975038lp',
 '52558000aaa',
 'visi7k1yr',
 'trabajonet9',
 '0169395484a',
 'memjan123',
 'faranumar91',
 'czuodhj972',
 'prisonbreak1',
 'memjan123',
 'faranumar91',
 'visi7k1yr',
 '0169395484a',
 'fk9qi21m',
 'prisonbreak1',
 'go7kew7a2po',
 'yqugu927',
 'juliel009',
 'as326159',
 'sbl571017',
 'kino3434',
 'pHyqueDIyNQ8vmhb',
 'megzy123',
 'olmaz.',
 '52558000aaa',
 'universe2908',
 'idofo673',
 'as326159',
 'calcifer32',
 'alimagik1',
 'AVYq1lDE4MgAZfNt',
 'lsdlsd1',
 'kswa2mrv',
 'TyWM72UNEex8Q8Y',
 'c3h8bkzr',
 'memjan123',
 'prisonbreak1',
 'yitbos77',

#### Converting words in characters

In [14]:
def word_divide_char(input):
    characters=[]
    for i in input:
        characters.append(i)
    return characters

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(tokenizer=word_divide_char)
X=tfidf.fit_transform(X)

In [16]:
tfidf.vocabulary_

{'k': 60,
 'z': 75,
 'd': 53,
 'e': 54,
 '5': 33,
 '7': 35,
 'i': 58,
 'n': 63,
 'o': 64,
 '3': 31,
 '4': 32,
 'm': 62,
 'g': 56,
 'y': 74,
 '1': 29,
 '2': 30,
 'a': 50,
 'v': 71,
 'q': 66,
 'l': 61,
 'f': 55,
 't': 69,
 'u': 70,
 '6': 34,
 'c': 52,
 '8': 36,
 'h': 57,
 'w': 72,
 's': 68,
 '9': 37,
 'r': 67,
 '0': 28,
 'b': 51,
 'j': 59,
 'p': 65,
 '.': 26,
 'x': 73,
 '@': 43,
 '-': 25,
 '&': 20,
 '?': 42,
 '>': 41,
 '<': 39,
 '!': 15,
 '_': 48,
 ';': 38,
 '±': 86,
 ' ': 14,
 '#': 17,
 '/': 27,
 '%': 19,
 'ú': 119,
 '*': 23,
 '$': 18,
 '^': 47,
 'þ': 123,
 'ó': 113,
 ')': 22,
 '{': 76,
 '}': 78,
 '(': 21,
 '=': 40,
 '[': 44,
 '\x1c': 12,
 '`': 49,
 '³': 88,
 ']': 46,
 '+': 24,
 'ô': 114,
 '¿': 97,
 '~': 79,
 '\\': 45,
 '\x16': 7,
 'ò': 112,
 '·': 92,
 '\x1e': 13,
 'ä': 102,
 '\x19': 10,
 'õ': 115,
 '|': 77,
 'ð': 110,
 'å': 103,
 'â': 101,
 'à': 99,
 '"': 16,
 '\x10': 4,
 '\x17': 8,
 'ß': 98,
 '«': 84,
 '¾': 96,
 '´': 89,
 '²': 87,
 '\x05': 0,
 '\x1b': 11,
 'ÿ': 124,
 '\x7f': 80,
 'º':

In [17]:
df['password'][0]

'kzde5577'

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=.20, random_state=0)

In [19]:
from sklearn.linear_model import LogisticRegression
log_reg=LogisticRegression(penalty='l2', multi_class='ovr')
log_reg.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='ovr', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [20]:
log_reg.score(X_train, y_train)

0.8135748565924538

#### 0 : Week password
#### 1 : Password strength is good
#### 2 : Password strength is strong

In [21]:
x_predict=np.array(['abc'])
x_predict=tfidf.transform(x_predict)
y_predict=log_reg.predict(x_predict)
y_predict

array([0])

In [22]:
from xgboost import XGBClassifier
xgb=XGBClassifier()
xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='multi:softprob', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [23]:
y_predict=xgb.predict(X_test)
y_predict

array([1, 0, 1, ..., 1, 1, 1])

In [26]:
import seaborn as sns

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, average_precision_score, recall_score
confusion_matrix(y_test,y_predict)

array([[10321,  7519,     4],
       [ 1413, 97299,   856],
       [    9,  1554, 14953]], dtype=int64)